# Generated by Django 5.2 on 2025-10-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Причина бана', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='Бан до (оставьте пустым для постоянного бана)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
