# Generated by Django 5.2 on 2025-10-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sticker',
            field=models.CharField(blank=True, help_text='Эмодзи или стикер для комментария', max_length=100, null=True),
        ),
    ]
